version: "3"

services:
  postgres:
    container_name: app_medical-postgres
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_DATABASE:-app_medical_dev}
      POSTGRES_USER: ${DB_USER:-root}
      POSTGRES_PASSWORD: ${DB_PASS:-root}
volumes:
  postgres:
